// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating visual prompts for creatives.
 *
 * The flow uses the (X)promptor module to generate visual prompts to help creatives quickly come up with new art ideas.
 *
 * @module ai/flows/generate-visual-prompts
 *
 * @interface GenerateVisualPromptsInput - The input type for the generateVisualPrompts function.
 * @interface GenerateVisualPromptsOutput - The output type for the generateVisualPrompts function.
 * @function generateVisualPrompts - The function that generates visual prompts based on the input.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateVisualPromptsInputSchema = z.object({
  topic: z.string().describe('The topic or theme for the visual prompt.'),
  style: z.string().optional().describe('The desired art style (e.g., abstract, photorealistic, surreal).'),
  medium: z.string().optional().describe('The art medium (e.g., painting, digital art, sculpture).'),
  mood: z.string().optional().describe('The desired mood or atmosphere (e.g., happy, sad, mysterious).'),
});

export type GenerateVisualPromptsInput = z.infer<typeof GenerateVisualPromptsInputSchema>;

const GenerateVisualPromptsOutputSchema = z.object({
  prompt: z.string().describe('A creative visual prompt based on the input parameters.'),
});

export type GenerateVisualPromptsOutput = z.infer<typeof GenerateVisualPromptsOutputSchema>;

/**
 * Generates a visual prompt using the provided input.
 * @param input - The input parameters for generating the visual prompt.
 * @returns A promise that resolves with the generated visual prompt.
 */
export async function generateVisualPrompts(input: GenerateVisualPromptsInput): Promise<GenerateVisualPromptsOutput> {
  return generateVisualPromptsFlow(input);
}

const generateVisualPromptsPrompt = ai.definePrompt({
  name: 'generateVisualPromptsPrompt',
  input: {
    schema: GenerateVisualPromptsInputSchema,
  },
  output: {
    schema: GenerateVisualPromptsOutputSchema,
  },
  prompt: `You are a visual prompt generator designed to inspire creatives.

  Based on the topic, style, medium, and mood provided, generate a creative and detailed visual prompt that an artist can use as inspiration for their next artwork.

  Topic: {{{topic}}}
  Style: {{{style}}}
  Medium: {{{medium}}}
  Mood: {{{mood}}}

  Visual Prompt:`,
});

const generateVisualPromptsFlow = ai.defineFlow(
  {
    name: 'generateVisualPromptsFlow',
    inputSchema: GenerateVisualPromptsInputSchema,
    outputSchema: GenerateVisualPromptsOutputSchema,
  },
  async input => {
    const {output} = await generateVisualPromptsPrompt(input);
    return output!;
  }
);
