// This is an autogenerated file from Firebase Studio. Do not edit.
// Important: This file is used by both the Genkit Dev UI and the Next.js app.

import { config } from 'dotenv';
config();

// All AI-related imports should be placed here.
import './genkit';
import './flows/code-actions';
import './flows/copilot-lyrics';
import './flows/create-folder';
import './flows/debug-code';
import './flows/delete-document';
import './flows/delete-folder';
import './flows/explain-code';
import './flows/generate-code';
import './flows/generate-creative-ideas';
import './flows/generate-deck';
import './flows/generate-flux';
import './flows/generate-frame';
import './flows/generate-ideas';
import './flows/generate-image';
import './flows/generate-moodboard';
import './flows/generate-motion';
import './flows/generate-muse';
import './flows/generate-nexus';
import './flows/generate-palette';
import './flows/generate-persona';
import './flows/generate-schedule';
import './flows/generate-sound';
import './flows/generate-text';
import './flows/generate-tone';
import './flows/generate-visual-prompts';
import './flows/generate-voice';
import './flows/get-signed-url';
import './flows/list-documents';
import './flows/oria';
import './flows/parse-event';
import './flows/refactor-code';
import './flows/reformat-text-with-prompt';
import './flows/rename-document';
import './flows/share-document';
import './flows/upload-document';
